version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - NODE_ENV: TEST
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn versions
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint & Test
          command: yarn test:prod
      - run:
          name: Build
          command: yarn build
      - run:
          name: Report Coverage
          command: yarn report-coverage
      - store_artifacts:
          path: ./dist
          destination: dist
      - store_artifacts:
          path: ./coverage
          destination: coverage
      - store_artifacts:
          path: ./docs
          destination: docs
      - store_test_results:
          path: ./coverage
  release:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Build library
          command: yarn build
      - run:
          name: Deploy release
          command: yarn semantic-release
      - run:
          name: Deploy docs
          command: yarn deploy-docs

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
